### ISSUE TITLE
Extra comma in json file

### ISSUE THREAD

**Issue by NoMathExpectation** [DPS2004/rdtradingcards#73]
There is an extra comma in `act5.json`, which will make json fail to load:

https://github.com/DPS2004/rdtradingcards/commit/8feab11c415579e3f1d7dc902baeb16d39eae274#diff-5d7ca112e312534b92f8d0371657e5a5ed0fe2c53de24f0333c77f65d62d9772R125

**Comment by DPS2004** [comment]
it seems to load fine for me when running it?

**Comment by DPS2004** [comment]
some json parsers are more strict than others. the one I use in this project allows for trailing commas, but it looks like yours doesn't. I'll remove the trailing comma so you can load it easier, but in the future i cant guarantee compatibility with code that isn't mine
